language: python
python:
  - "3.7"
dist: xenial
install:
  - pip install -r requirements.txt
  - pip install .
env:
  - FLASK_ENV="development" PHONE_FORWARD_NUMBER="+12223334444" TWILIO_AUTH_TOKEN="1111000022223333ffff00001111aacc" PHONE_CONF_ROOM_NUMBER=1234 PHONE_CONF_LEADER_PIN=9876 PHONE_CONF_PARTICIPANT_PIN=4567
script:
  - pylint phone/ --errors-only
  - pytest
