runtime: python37
entrypoint: gunicorn -b :$PORT phone:gunicorn_app
handlers:
- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto
env_variables:
  PHONE_FORWARD_NUMBER: ''
  TWILIO_AUTH_TOKEN: ''
